/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class History with the namespace ch.ivyteam.ivy.cluster
 */
package ch.ivyteam.ivy.cluster;

/**
 */
public class History extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = 2919618239926263539L;

  /**
   * In millis
   */
  private java.lang.Number start;

  /**
   * Gets the field start.
   * @return the value of the field start; may be null.
   */
  public java.lang.Number getStart()
  {
    return start;
  }

  /**
   * Sets the field start.
   * @param _start the new value of the field start.
   */
  public void setStart(java.lang.Number _start)
  {
    start = _start;
  }

  /**
   * In millis
   */
  private java.lang.Number end;

  /**
   * Gets the field end.
   * @return the value of the field end; may be null.
   */
  public java.lang.Number getEnd()
  {
    return end;
  }

  /**
   * Sets the field end.
   * @param _end the new value of the field end.
   */
  public void setEnd(java.lang.Number _end)
  {
    end = _end;
  }

}
