/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class ResumeTask with the namespace ch.ivyteam.ivy.cluster
 */
package ch.ivyteam.ivy.cluster;

/**
 */
public class ResumeTask extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = 7765810833826110031L;

  /**
   */
  private java.lang.String taskStartUri;

  /**
   * Gets the field taskStartUri.
   * @return the value of the field taskStartUri; may be null.
   */
  public java.lang.String getTaskStartUri()
  {
    return taskStartUri;
  }

  /**
   * Sets the field taskStartUri.
   * @param _taskStartUri the new value of the field taskStartUri.
   */
  public void setTaskStartUri(java.lang.String _taskStartUri)
  {
    taskStartUri = _taskStartUri;
  }

}
