services:
  db:
    image: mariadb:12.0.2
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
     - ./mariadb/ivy.cnf:/etc/mysql/conf.d/ivy.cnf

  loadbalancer:
    image: bitnami/apache
    user: root
    ports:
     - 9080:8080
    volumes:
     - ./apache-conf/apache-host.conf:/opt/bitnami/apache/conf/vhosts/apache-host.conf:ro
     - ./apache-conf/members.conf:/opt/bitnami/apache/conf/vhosts/members.conf:ro

  ivy1:
    image: axonivy-engine-cluster-test:latest
    ports:
     - 9081:8080
    deploy:
      resources:
        limits:
          cpus: '2' 

  ivy2:
    image: axonivy-engine-cluster-test:latest
    ports:
     - 9082:8080
    deploy:
      resources:
        limits:
          cpus: '2' 

  ivy3:
    image: axonivy-engine-cluster-test:latest
    ports:
     - 9083:8080
    deploy:
      resources:
        limits:
          cpus: '2' 

  ivy4:
    image: axonivy-engine-cluster-test:latest
    ports:
     - 9084:8080
    deploy:
      resources:
        limits:
          cpus: '2' 
          
networks:
  default:
    external:
      name: ivycluster
