services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    command: postgres -c 'max_connections=1000'

  loadbalancer:
    build: apache-conf
    user: root
    ports:
     - 9080:8080
    volumes:
     - ./apache-conf/apache-host.conf:/usr/local/apache2/conf/vhost.conf:ro
     - ./apache-conf/members.conf:/usr/local/apache2/conf/members.conf:ro

  ivy1:
    image: axonivy/axonivy-engine:dev
    volumes:
      - ./apps:/ivy/applications
      - ./ivy.yaml:/ivy/configuration/ivy.yaml
      - ./log4j2.xml:/ivy/configuration/log4j2.xml
      - ./license.lic:/ivy/configuration/license.lic
    ports:
     - 9081:8080
    deploy:
      resources:
        limits:
          cpus: '2' 

  ivy2:
    image: axonivy/axonivy-engine:dev
    volumes:
      - ./apps:/ivy/applications
      - ./ivy.yaml:/ivy/configuration/ivy.yaml
      - ./log4j2.xml:/ivy/configuration/log4j2.xml
      - ./license.lic:/ivy/configuration/license.lic
    ports:
     - 9082:8080
    deploy:
      resources:
        limits:
          cpus: '2' 

  ivy3:
    image: axonivy/axonivy-engine:dev
    volumes:
      - ./apps:/ivy/applications
      - ./ivy.yaml:/ivy/configuration/ivy.yaml
      - ./log4j2.xml:/ivy/configuration/log4j2.xml
      - ./license.lic:/ivy/configuration/license.lic
    ports:
     - 9083:8080
    deploy:
      resources:
        limits:
          cpus: '2' 

  ivy4:
    image: axonivy/axonivy-engine:dev
    volumes:
      - ./apps:/ivy/applications
      - ./ivy.yaml:/ivy/configuration/ivy.yaml
      - ./log4j2.xml:/ivy/configuration/log4j2.xml
      - ./license.lic:/ivy/configuration/license.lic
    ports:
     - 9084:8080
    deploy:
      resources:
        limits:
          cpus: '2' 
          
networks:
  default:
    external:
      name: ivycluster
